port: "8003"
base_url: http://localhost:8003/api/

database:
  driver: pgsql
  host: localhost
  username: postgres
  password: root
  name: 
  port: "5432"
  sslmode: prefer
  timezone: Asia/Shanghai
  dsn: 

mongo:
  dns: mongodb://localhost:27017